### PR TITLE
Added platform to the config

### PR DESCRIPTION
**Pull request by freberkivra**
Adding configuration for device.platform that we're using for OS distribution.

### CODE REVIEW

**Comment by KivraChristoffer** [comment]
This is something we been using in our local fork for some time, now as master supports newer versions of netbox, we would like to see this included so we can stop using our fork and use master.

**Comment by cyrinux** [comment]
Hi guys,
Can you tell me more about this, can you give me some example of "plateform"?
From what i understand we should be able to fetch it from `/etc/lsb_release` or other way to get the OS.

**Comment by cyrinux** [comment]
Hi @KivraChristoffer can you please paste me some strings of possible values you actually got, i want to be sure to well understand what you got here. 
Thanks

**Comment by KivraChristoffer** [comment]
Hi,
Sure, we might not use is like its intended, as we use this to store os information

- CentOS Linux 7.9
- FreeBSD FreeBSD 11.2
- Ubuntu Linux 20.04



( for now i found a issue with it when its not defined. so please wait for a update )

**Comment by KivraChristoffer** [comment]
Hi,
Yes it could be.
We did have some special usage of it ( using it as liimiters then using netbox as a ansible inventory )
Screenshot from 2022-03-31 11-41-46

**Comment by cyrinux** [comment]
I will commit on this branch my idea asap.

**Comment by cyrinux** [comment]
@KivraChristoffer @freberkivra can you please try this PR ? https://github.com/Solvik/netbox-agent/pull/216/files

It superseed this one, I added a commit with a try of auto-detection base on the old module platform deprecated is recent version but we still use python3.6 actually.
The goal is to fallback to autodetection, you can still force the version with the flag.

Waiting for your test, thanks

**Pull request closed without merging**
