### PR TITLE
Support Netbox 3

### PR DESCRIPTION
**Pull request by CllaudiaB**
- [x] update dependencies
- [x] replace device_role with role for Netbox 3.6 : https://github.com/netbox-community/netbox/issues/6391
- [x] new cabling models from Netbox 3.3: https://github.com/netbox-community/netbox/issues/9102

### CODE REVIEW

**Comment by ribetm** [comment]
Fixes #303 and #240 (superseding #277)
Maybe #275 as a side effect

**Comment by c0ff3e** [comment]
Happy to see some life here,
how can i assist ?
there is some other MR thats would be nice to include in the same time.

**Comment by ribetm** [comment]
> Happy to see some life here, how can i assist ? there is some other MR thats would be nice to include in the same time.

Which MRs are you thinking of ? Maybe we could have them separated, unless these are linked to Netbox 3 compatibility ?

Let's merge this so the others can be rebased and tested directly

**Comment by c0ff3e** [comment]
> > Happy to see some life here, how can i assist ? there is some other MR thats would be nice to include in the same time.
> 
> Which MRs are you thinking of ? Maybe we could have them separated, unless these are linked to Netbox 3 compatibility ?
> 
> Let's merge this so the others can be rebased and tested directly
Make lshw scrpping more resilient #292

there where some others i used also. will update when i find them.

**Pull request merged**
