### PR TITLE
Add HP Moonshot 1500 support

### PR DESCRIPTION
**Pull request by cyrinux**
Hi,

I add the support of hp moonshot 1500 with ProLiant m750, m710x and m750 server cartridge.
I take the decison after digging a lot to declare that a moonshot is like a "blade".

(little linting btw)
Hope this help,

Regards,

### CODE REVIEW

**Comment by Solvik** [comment]
thanks for this new hardware support @cyrinux !!
would you be able to commit a dmidecode output and put it in a few tests ?

**Comment by cyrinux** [comment]
> thanks for this new hardware support @cyrinux !!
> would you be able to commit a dmidecode output and put it in a few tests ?

Sure, i try to do this and ping you if I dont find how to do :D

**Comment by cyrinux** [comment]
I add a test about getting the two serial numbers, it pass in tox pytest. Is it OK for you?

**Comment by Solvik** [comment]
awesome 👍

**Pull request merged**
