### PR TITLE
Virtualmachine corrections

### PR DESCRIPTION
**Pull request by obeone**
I add  missing debug print (--debug was failing on a VM).

And if lldp is enabled and we are on a VM, multiple errors occurred. I add some checks.

And last thing, maybe it has to be in a separate PR (but for one line...), main now return 0 if everything was ok, as it's what a shell except

### CODE REVIEW

**Comment by Solvik** [comment]
Hi @obeone 

Thanks for this second PR
Could you remove the update to requirements.txt as it's already handled by your other PR ?

Thanks

**Comment by obeone** [comment]
Yes !
Sorry, I realized after that this branch embedded the other PR, and I was hoping you'll accept the other one 😄

I do that soon !

**Comment by sinavir** [comment]
Hello, any updates on this ? I felt in this issue when trying to use netbox-agent

**Comment by CllaudiaB** [comment]
Hello @obeone
Can you just keep the suggestions for Virtual Machine in this branch? 
So that I can merge your PR

**Pull request merged**
