### PR TITLE
Some fixes that prevent crash on register new a server

### PR DESCRIPTION
**Pull request by cyrinux**
Hi @Solvik,

I'm trying to continue the deployment of netbox-agent and updating it by the way where you know maybe :)

Will push some fix like this while I progress and try to bring feature if I got ideas :)

Regards,

### CODE REVIEW

**Comment by ramnes** [comment]
Can you please make a dedicated commit for style changes? Right now it's pretty hard to see what you're actually fixing, there's simply too much noise.

**Comment by cyrinux** [comment]
Sure sorry, I forgot to disable my formatter on my last commit. 
What do you think about using the python black formatter?

**Comment by ramnes** [comment]
Feel free to open an issue about this! (Spoiler: I'd prefer not to, but then it's mostly about what @Solvik wants.)

**Comment by cyrinux** [comment]
No problem for black, not my priority for the moment, i just need to disable it ;)

**Pull request merged**
